/** Map UI waste type labels to backend wasteTypeId for vision weight API */
export const LABEL_TO_WASTE_TYPE_ID: Record<string, string> = {
  "Paddy Husk": "AGR_001",
  "Rice Straw": "AGR_001",
  "Rice Husk": "AGR_001",
  "Wheat Straw": "AGR_001",
  "Barley Straw": "AGR_001",
  "Oat Straw": "AGR_001",
  "Corn Stalks": "AGR_003",
  "Maize Cob": "AGR_003",
  "Sugarcane Bagasse": "AGR_002",
  "Coconut Shells": "COCO_SHL",
  "Groundnut Shell": "AGR_001",
  "Cotton Stalk": "AGR_001",
  "Mustard Stalk": "AGR_001",
  "Soybean Stalk": "AGR_001",
  "Sunflower Stalk": "AGR_001",
  "Palm Empty Fruit Bunch": "AGR_005",
  "Coffee Husk": "AGR_004",
  "Tea Waste": "AGR_001",
  "Banana Waste": "FOD_002",
  "Mango Waste": "FOD_002",
  "Vegetable Waste": "FOD_002",
  "Fruit Waste": "FOD_002",
  "Jute Stalk": "AGR_001",
  "Castor Stalk": "AGR_001",
  "Sesame Stalk": "AGR_001",
  "Potato Vine": "FOD_002",
  "Tomato Waste": "FOD_002",
  "Gram / Chickpea Stalk": "AGR_001",
  "Tur / Pigeon Pea Stalk": "AGR_001",
  "Oilseed Waste": "AGR_001",
  "Brewery Spent Grains": "FOD_001",
  "Sorghum Stalk": "AGR_001",
  "Rye Straw": "AGR_001",
  "Millet Straw": "AGR_001",
  "Lentil Stalk": "AGR_001",
  "Cowpea / Black-Eyed Pea Stalk": "AGR_001",
  "Bean Stalk": "AGR_001",
  "Rapeseed / Canola Stalk": "AGR_001",
  "Olive Pomace": "FOD_002",
  "Cocoa Pod Husk": "AGR_004",
  "Tobacco Stalk": "AGR_001",
  "Hemp Stalk": "AGR_001",
  "Cassava Peel / Residue": "FOD_002",
  "Citrus Waste": "FOD_002",
  "Grape Pomace": "FOD_002",
  "Almond Shell": "AGR_001",
  "Cashew Shell": "COCO_SHL",
  "Pea Stalk": "AGR_001",
  "Other Agricultural Waste": "AGR_001",
};

export function getWasteTypeId(label: string): string {
  return LABEL_TO_WASTE_TYPE_ID[label] || "AGR_001";
}
