-- Vision weight estimation log (optional MySQL; app works without this table)
CREATE TABLE IF NOT EXISTS weight_estimations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  listing_id INT NULL,
  user_id INT NOT NULL,
  waste_type_id VARCHAR(10) NOT NULL,
  image_hash VARCHAR(64) NOT NULL COMMENT 'SHA256 of uploaded image',
  estimated_weight_kg DECIMAL(12,3) NOT NULL,
  estimated_weight_tonnes DECIMAL(12,6) NOT NULL,
  weight_range_min_kg DECIMAL(12,3),
  weight_range_max_kg DECIMAL(12,3),
  confidence_percent TINYINT UNSIGNED,
  volume_cubic_metres DECIMAL(10,4),
  density_used_kg_m3 DECIMAL(8,2),
  geometry_assumed VARCHAR(100),
  estimation_method VARCHAR(200),
  anchors_used JSON COMMENT 'Array of anchor strings used',
  material_confirmed BOOLEAN DEFAULT FALSE,
  waste_type_detected VARCHAR(200),
  reasoning TEXT,
  warning_flags JSON,
  improvement_suggestions JSON,
  optional_reference_object VARCHAR(200) NULL,
  optional_measurement VARCHAR(200) NULL,
  text_found_in_image JSON NULL,
  image_angle VARCHAR(30),
  frame_coverage_percent TINYINT UNSIGNED,
  waste_credit_preview DECIMAL(10,4),
  processing_time_ms INT,
  gemini_model_version VARCHAR(50) DEFAULT 'gemini-1.5-pro-vision',
  vision_api_version VARCHAR(20) DEFAULT 'v1',
  user_confirmed_weight_kg DECIMAL(12,3) NULL COMMENT 'Actual weight user enters after weighing',
  accuracy_delta_percent DECIMAL(6,2) NULL COMMENT 'Populated when user confirms actual weight',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_listing (listing_id),
  INDEX idx_user (user_id),
  INDEX idx_waste_type (waste_type_id),
  INDEX idx_confidence (confidence_percent)
);
